### PR TITLE
option to disable building tests

### PR DESCRIPTION
**Pull request by PeterMitrano**

### CODE REVIEW

**Comment by dmcconachie** [comment]
I'm presuming this will need changes in the docker/travis CI setup? @bsaund

**Comment by dmcconachie** [comment]
Also, presumably any things that are `find_packaged` that are test only (`GTest`?) should presumably be inside the if block.

**Comment by bsaund** [comment]
The standard flag I see is ros packages is:
CATKIN_ENABLE_TESTING

Is there a reason to use a custom option here?

**Comment by PeterMitrano** [comment]
No we should use the standard flag for sure

**Comment by PeterMitrano** [comment]
ok brad lmk if this looks good

**Pull request merged**
