### PR TITLE
Include all headers in the CMake custom target

### PR DESCRIPTION
**Pull request by bsaund**
With the reorganization, many headers were not included in the CMake custom target.
This caused clion to complain when opening some files

Note: Review and merge https://github.com/UM-ARM-Lab/arc_utilities/pull/106 first. The diff will be a lot smaller

### CODE REVIEW

**Comment by PeterMitrano** [comment]
I'm confused -- looks like all that changed here was formatting, and even then the formatting is inconsistent. Are we using 2 or 4 spaces for indentation?

**Comment by bsaund** [comment]
This is clions autoformat. I'm not sure why it likes this spacing.

New lines are added including the new files you created

**Comment by bsaund** [comment]
The indenting seems fine. 2 spaces for indentation, but more (8?) for a line continuation. All of the include statements are line continuations

**Comment by PeterMitrano** [comment]
But look at the indentation at the end of the file -- some continuation indents are only 4 not 8. What are you clion settings, and are y ou sure you formatting the whole file not just a selection?

**Comment by PeterMitrano** [comment]
also on line 7 there's a continuation indent that's only 4 spaces

**Comment by bsaund** [comment]
Fixed.
Pretty sure clion did not update the later lines to "make things look like surrounding"

**Comment by PeterMitrano** [comment]
screenshot_11-26-20_10:41:18
 this is what my settings look like, I think these are the default

**Comment by PeterMitrano** [comment]
LGTM I'll merge once travis finishes

**Pull request merged**
