### PR TITLE
Added Listener wrapper around subscriber, to reduce boilder plate code

### PR DESCRIPTION
**Pull request by bsaund**
I'm hoping for comments like: "This is genius", "ROS already does this using [link]", or "this is dumb because [reason]"

### CODE REVIEW

**Comment by ChuplesKai** [comment]
In my experience, having something like this can be quite useful, but it does require some careful use.

For some applications, you will want the behavior of "consuming" the message after you have read it once, rather than reading the same message over and over.  For instance, you may have something listening in on a "joint_control" topic which sends joint velocities... simply running the same velocity over and over might be bad.  This can always be fixed by being careful about message timestamps, but that means putting timestamp-checking code around any Listener where this is a problem.

It might not even be a big deal, but perhaps we should also consider having a version which consumes the data once it has been read, so that you can only read each message once.

**Comment by bsaund** [comment]
When we want a "consuming" behavior, I envisioned using the standard ros callback pattern, not using this listener at all.
That being said, we could easily add a "is_new_data()" method. 

Regarding timestamps, it would also be reasonable to check for a header field, and only overwrite self.data if the timestamp is newer.

**Comment by ChuplesKai** [comment]
Right, any one of those is probably reasonable.  It is probably simplest to ensure that anybody who uses this realizes they need to use the standard ROS callback when they want consuming behavior.

**Comment by bsaund** [comment]
I added documentation to this effect, and removed the optional lock as I can't see when it would be useful.
I'll wait for Dale's comments, if he survives the paper deadline.

**Comment by bsaund** [comment]
@dmcconachie  You pre-empted my next change :)

**Pull request merged**
